#!/usr/bin/python

import argparse
from fileinput import filename

parser = argparse.ArgumentParser(description='genefiles')

parser.add_argument('filename', type=argparse.FileType('r'), help='Insert a File name')
parser.add_argument('-t', '--TaxID', type=str, nargs='+', action='store', required='true', help='Add ID Values')
args = parser.parse_args()

#Dictionary
d2 = {'Synonyms': 1}
d = vars(args)
d.update(d2)
print(d)


# print(args.TaxIdList)

ln = args.filename.read().splitlines('\t')

count = 0
for TaxID in ln:

    count += 1
ln.readline().split

print(count)







#     print( args.TaxID)
# #print(ln)
# # print(input)





# -04/03/20: Def count
#
# def count_char(ln):
#     countNum= 0
#     for TaxIdList in ln:
#         if (TaxIdList in ln):
#             countNum[TaxIdList] +=1
#         else:
#             countNum[TaxIdList] = 1
#     return countNum
# #
# # #     for args.TaxID in ln:
# # #         countNum = 0
# # #         if args.TaxID in ln:
# #             countNum +=1
# #         else:
# #             return "ID Not Found"
#

#
#
#
#
# # len(set(open(yourdictfile).read().split()))
# #

#
#
#
#
#
#
#
# # ------------------04/02/2020---------------------------------
# # TaxID Argument:: Error: error: argument numberInput: invalid int value: 'All_Data.gene_info'
# # parser = argparse.ArgumentParser(description='TaxID')
# # parser.add_argument('numberInput', type=int, nargs='+', help='an integer for TaxID')
# # results = parser.parse_args()
#
#
# # usr_str_input = input('Input ID Num:')
# # for file_str_input in fr:
# #     if usr_str_input in file_str_input.split('\t'):
# #         for usr_str_input in file_str_input:
# #             occur += 1
# #         print("There are", occur, "Genes ID's in this Tax ID")
# # print args.filename.readlines()
# with open(args.filename) as infile:
# print('TaxIDs = {!r}'.format(args.TaxIDs))
